### ISSUE TITLE
shp2pgsql  funciona no Windows

### ISSUE THREAD

**Issue by yjmenezes** [kylefelipe/qgis-tips-tricks#2]
@FelipeSBarros 

Valeu !
No Windows, o procedimento shp2pgsql  roda em Terminal OsGeo  ou teria de adaptar para o Windows command.com ?

**Comment by FelipeSBarros** [comment]
@yjmenezes , fiz uma pesquisa basica aqui. Há um shp2pgsql.exe, sim.
Mas não consegui entender se já vem na instalação ou se é um executável a ser adquirido extra instalação.
Além disso, acho que deve mudar algumas coisas em relação ao loop e organização dos comandos.
Em resumo, não saberia dar certeza.

**Comment by FelipeSBarros** [comment]
Neste link mostra como usá-lo: [PostGIS Tutor 01](http://www.bostongis.com/PrinterFriendly.aspx?content_name=postgis_tut01). Dê juma olhada em "Loading the Data"

**Comment by yjmenezes** [comment]
@FelipeSBarros , obrigado, vou ler o link.

Bom saber que existe o shp2pgsql.exe para ambiente grafico Windows.
A sintaxe de "bash" difere do "command.com" mas eh uma questao de adaptar.

@All,
abri um "issue" para que vejam como podem colocar questoes ou participar de uma questao.
Vou fechar mas podem reabrir se necessario.

**Comment by yjmenezes** [comment]
Reabrindo, participem...
